### ISSUE TITLE
How the 7B model is needing 6xA100 in fp16 ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [zsc/llama_infer#1]
I was able to load this model in 15 gigs vram in the original llama

**Comment by zsc** [comment]
The listed numbers are for for the 65B model (just updated README.md to clarify on this). Note that I didn't tweak the device_map for the case of A100 fp16. I expect it would be possible to reduce to somewhere near 4xA100-40G .

The VRAM usage seems reasonable with hugging face wrapper, 65B amounts 130GB fp16 weights, and should fit into 4x40G = 160GB, which is 4xA100-40G.

**Comment by MohamedAliRashad** [comment]
@zsc This makes more sense, thanks for the great work
